#pragma once

#define MENU_OPTION_COLOR_NORMAL 0x7BCF
#define MENU_OPTION_COLOR_HOVER 0xA534

#define MENU_OPTION_START_GAME_X 265
#define MENU_OPTION_START_GAME_Y 300
#define MENU_OPTION_START_GAME_WIDTH 750
#define MENU_OPTION_START_GAME_HEIGHT 90
#define MENU_OPTION_START_GAME_DESCRIPTION "start game"

#define MENU_OPTION_END_GAME_X 265
#define MENU_OPTION_END_GAME_Y 450
#define MENU_OPTION_END_GAME_WIDTH 750
#define MENU_OPTION_END_GAME_HEIGHT 90
#define MENU_OPTION_END_GAME_DESCRIPTION "end game"

#define MENU_OPTION_SCOREBOARD_X 265
#define MENU_OPTION_SCOREBOARD_Y 600
#define MENU_OPTION_SCOREBOARD_WIDTH 750
#define MENU_OPTION_SCOREBOARD_HEIGHT 90
#define MENU_OPTION_SCOREBOARD_DESCRIPTION "scoreboard"

#define MENU_OPTION_MULTIPLAYER_X 265
#define MENU_OPTION_MULTIPLAYER_Y 750
#define MENU_OPTION_MULTIPLAYER_WIDTH 750
#define MENU_OPTION_MULTIPLAYER_HEIGHT 90
#define MENU_OPTION_MULTIPLAYER_DESCRIPTION "multiplayer"

#define MENU_TITLE_X 384
#define MENU_TITLE_Y 100
#define MENU_TITLE "wordlcom"
